CREATE TABLE Albunes(
		ID		INT IDENTITY(1,1),
		Titulo	VARCHAR(50),
		Tags	VARCHAR(100),		 
		Portada	VARCHAR(MAX),
)
GO

CREATE TABLE Contacto(
	Portada		VARCHAR(16) NOT NULL,
	Tel			VARCHAR(50)NOT NULL,
	Email		VARCHAR(50)NOT NULL,
	Facebook	VARCHAR(50)NOT NULL,
	Flickr		VARCHAR(50)NOT NULL, 
	Titulo		VARCHAR	(50)NOT NULL,	 
	Subtitulo	VARCHAR(50)NOT NULL,
	Texto1		VARCHAR(400)NOT NULL,
	Texto2		VARCHAR(400)NOT NULL
)
GO

CREATE TABLE Fotos (
	ID			INT NOT NULL IDENTITY(1,1),
	SRC			VARCHAR(MAX),
	ID_Album	INT NOT NULL
)
GO

CREATE TABLE Portadas (
	ID		INT		IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Texto	VARCHAR(50),
	SRC		VARCHAR(MAX)
)
GO

CREATE TABLE SobreMi (
	Portada		VARCHAR(MAX),
	Titulo		VARCHAR(100),
	Subtitulo	VARCHAR(100),
	Texto1		VARCHAR(MAX),
	Texto2		VARCHAR(MAX),
	Texto3		VARCHAR(MAX)	 

)
GO

CREATE TABLE Usuarios(
	Usuario		VARCHAR(50),
	Password	VARCHAR(MAX)
)
GO